In [ ]:
import pandas as pd

In [ ]:
from google.colab import files
uploaded= files.upload()

Saving dirty_financial_transactions.csv to dirty_financial_transactions (1).csv

In [ ]:
df=pd.read_csv("dirty_financial_transactions.csv")
df.head()

,Transaction_ID,Transaction_Date,Customer_ID,Product_Name,Quantity,Price,Payment_Method,Transaction_Status
0,T0001,2024-08-02,C2205,Headphones,-5.0,$420.21,pay pal,NaN
1,T0002,2020-02-10,C3156,Coffee,469.0,-445.34202525395585,creditcard,Pending
2,T0003,2025-02-30,C2919,Tablet,-4.0,810.9930123946459,credit card,completed
3,T0004,2020-08-17,C3009,Tab,-7.0,868.6083413217348,PayPal,Pending
4,T0005,2025-02-30,C3488,Coffee Machine,-10.0,-763.1224490039416,PayPal,completed

In [ ]:
df.columns

Index(['Transaction_ID', 'Transaction_Date', 'Customer_ID', 'Product_Name',
       'Quantity', 'Price', 'Payment_Method', 'Transaction_Status'],
      dtype='object')

In [ ]:
df.shape
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 8 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Transaction_ID      94982 non-null   object
 1   Transaction_Date    95120 non-null   object
 2   Customer_ID         95122 non-null   object
 3   Product_Name        100000 non-null  object
 4   Quantity            94981 non-null   float64
 5   Price               66503 non-null   object
 6   Payment_Method      100000 non-null  object
 7   Transaction_Status  83321 non-null   object
dtypes: float64(1), object(7)
memory usage: 6.1+ MB

There are 100,000 rows and 8 columns.
Most data types are objects, with a single float by the quantity column. The percentage of missing values is 33% and transaction status 16%, which is quite large.

In [ ]:
#Check missing values
df.isnull().sum()

Transaction_ID         5018
Transaction_Date       4880
Customer_ID            4878
Product_Name              0
Quantity               5019
Price                 33497
Payment_Method            0
Transaction_Status    16679
dtype: int64

In [ ]:
#Calculate duplicates
df.duplicated().sum()

#df[df.duplicated()]

df['Transaction_ID'].duplicated().sum()
df[df['Transaction_ID'].duplicated()]

#remove duplicates(Keeps unique rows)
#df=df.drop_duplicates()
#to remove duplicates based on a column
#df=df.drop_duplicates(subset='Transaction_ID)

,Transaction_ID,Transaction_Date,Customer_ID,Product_Name,Quantity,Price,Payment_Method,Transaction_Status
90,NaN,2023-05-16,C308,Coffee Machine,824.0,577.5607699389858,creditcard,Failed
105,NaN,2025-02-30,C4261,Laptop,670.0,-197.03277785431612,pay pal,Failed
124,NaN,2021-12-02,C086,Coffee Machine,667.0,$-681.87,PayPal,Pending
140,NaN,2023-13-01,C869,Headphones,564.0,499.8782079245941,creditcard,Failed
146,NaN,2023-03-06,NaN,Headphones,-2.0,-574.740887890599,creditcard,Failed
...,...,...,...,...,...,...,...,...
99955,NaN,2020-07-23,C4753,Coffee Machine,9.0,876.2470391045515,PayPal,Pending
99973,NaN,2023-13-01,C918,Coffee Machine,702.0,NaN,credit card,Pending
99984,NaN,2022-01-26,C4753,Laptop,480.0,-558.7481358840021,Cash,completed
99995,NaN,2021-10-06,C1743,Headphones,-8.0,240.0032380562687,PayPal,complete
99999,T100000,2023-10-04,C1805,Tablet,2.0,89.37402345793535,PayPal,Failed

In [ ]:
#df['Transaction_ID'].head(20)

# Missing IDs
df['Transaction_ID'].isnull().sum()

# Check format consistency
df['Transaction_ID'].str.startswith('T').value_counts()

Transaction_ID
True    94982
Name: count, dtype: int64

In [ ]:
#Rebuild transaction_id numbering sequence
df['Transaction_ID'] = ['T' + str(i).zfill(4) for i in range(1, len(df)+1)]

df['Transaction_ID'].head(50)

0     T0001
1     T0002
2     T0003
3     T0004
4     T0005
5     T0006
6     T0007
7     T0008
8     T0009
9     T0010
10    T0011
11    T0012
12    T0013
13    T0014
14    T0015
15    T0016
16    T0017
17    T0018
18    T0019
19    T0020
20    T0021
21    T0022
22    T0023
23    T0024
24    T0025
25    T0026
26    T0027
27    T0028
28    T0029
29    T0030
30    T0031
31    T0032
32    T0033
33    T0034
34    T0035
35    T0036
36    T0037
37    T0038
38    T0039
39    T0040
40    T0041
41    T0042
42    T0043
43    T0044
44    T0045
45    T0046
46    T0047
47    T0048
48    T0049
49    T0050
Name: Transaction_ID, dtype: object

In [ ]:
#df.drop(columns=['Transaction ID'], inplace=True)
#df.info()

In [ ]:
df['Transaction_Date'].tail(50)

99950    2025-02-30
99951    2024-04-04
99952    2021-02-19
99953    2023-13-01
99954    2025-02-30
99955    2020-07-23
99956    2023-13-01
99957    2024-07-07
99958    2025-02-30
99959    2022-02-20
99960    2023-13-01
99961    2025-02-30
99962    2021-06-04
99963    2022-09-18
99964    2025-02-30
99965    2023-13-01
99966    2021-04-14
99967    2020-05-03
99968    2023-13-01
99969    2023-13-01
99970    2025-02-30
99971    2025-02-30
99972    2025-02-30
99973    2023-13-01
99974    2025-02-30
99975    2025-02-30
99976    2025-02-30
99977    2025-02-30
99978    2025-02-30
99979    2025-02-30
99980    2025-02-30
99981    2023-13-01
99982    2025-02-30
99983    2025-02-30
99984    2022-01-26
99985    2025-02-30
99986    2024-07-11
99987    2025-02-30
99988    2025-02-30
99989    2022-05-07
99990    2023-13-01
99991    2022-11-25
99992    2025-02-30
99993    2024-11-24
99994    2025-02-30
99995    2021-10-06
99996    2024-08-25
99997    2023-13-01
99998    2020-07-12
99999    2023-10-04
Name: Transaction_Date, dtype: object

In [ ]:
missing_transaction_date_rows = df[df['Transaction_Date'].isnull()]
display(missing_transaction_date_rows.head())

,Transaction_ID,Transaction_Date,Customer_ID,Product_Name,Quantity,Price,Payment_Method,Transaction_Status
8,T0009,NaN,C3387,Tablet,10.0,461.70198437439694,PayPal,NaN
43,T0044,NaN,C246,Smar,-10.0,NaN,Cash,Completed
58,T0059,NaN,C2809,Tablet,4.0,-329.6249100867068,credit card,NaN
61,T0062,NaN,C3832,Laptop,2.0,NaN,PayPal,Pending
88,T0089,NaN,C4555,Headphones,709.0,NaN,PayPal,completed

This code filters the DataFrame `df` to show only the rows where the `Transaction_Date` column has a missing value (`NaN`). I then display the first few rows of this filtered DataFrame.

In [ ]:
import numpy as np


# Convert 'Transaction_Date' to datetime, coercing invalid dates from NaN to NaT
df['Transaction_Date'] = pd.to_datetime(df['Transaction_Date'], errors='coerce')

# Recalculate missing count after coercing invalid dates
# NaT values are considered NaN by isnull()
current_missing_count = df['Transaction_Date'].isnull().sum()

# Get a list of valid, non-missing dates
valid_dates = df['Transaction_Date'].dropna()

# Fill missing Transaction Dates by randomly sampling from existing valid dates
# Only if there are valid dates to sample from and current_missing_count > 0
if not valid_dates.empty and current_missing_count > 0:
    df.loc[df['Transaction_Date'].isnull(), 'Transaction_Date'] = np.random.choice(valid_dates, current_missing_count)

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 8 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Transaction_ID      100000 non-null  object
 1   Transaction_Date    100000 non-null  datetime64[ns]
 2   Customer_ID         95122 non-null   object
 3   Product_Name        100000 non-null  object
 4   Quantity            94981 non-null   float64
 5   Price               66503 non-null   object
 6   Payment_Method      100000 non-null  object
 7   Transaction_Status  83321 non-null   object
dtypes: datetime64[ns](1), float64(1), object(6)
memory usage: 6.1+ MB

In [ ]:
df['Transaction_Date'].head(30)

0    2024-08-02
1    2020-02-10
2    2023-02-27
3    2020-08-17
4    2022-10-13
5    2021-10-26
6    2024-05-25
7    2021-06-14
8    2023-06-25
9    2021-05-06
10   2023-12-28
11   2021-08-24
12   2020-03-18
13   2020-06-19
14   2024-08-28
15   2023-01-31
16   2020-07-07
17   2021-01-26
18   2024-02-19
19   2020-09-10
20   2024-10-03
21   2021-12-17
22   2023-06-26
23   2023-11-03
24   2022-11-18
25   2020-01-01
26   2020-12-17
27   2023-03-04
28   2021-10-06
29   2021-10-16
Name: Transaction_Date, dtype: datetime64[ns]

In [ ]:
missing_customer_ids = df['Customer_ID'].isnull().sum()
print(f"Number of missing Customer_ID values: {missing_customer_ids}")

Number of missing Customer_ID values: 4878

In [ ]:
print("Sample rows with missing Customer_ID values:")
display(df[df['Customer_ID'].isnull()].head())

Sample rows with missing Customer_ID values:

,Transaction_ID,Transaction_Date,Customer_ID,Product_Name,Quantity,Price,Payment_Method,Transaction_Status
31,T0032,2023-10-05,NaN,Laptop,-7.0,NaN,Credit Card,Completed
49,T0050,2021-04-23,NaN,Tablet,-6.0,$969.72,PayPal,Completed
59,T0060,2023-12-29,NaN,Headphones,9.0,-774.7400993737688,pay pal,complete
81,T0082,2021-03-14,NaN,Laptop,2.0,-386.6519715886566,PayPal,NaN
119,T0120,2021-12-29,NaN,Coffee Machine,-7.0,159.45851825246467,PayPal,Failed

In [ ]:
# Filter rows where Customer_ID is missing
#missing_customer_id_rows = df[df['Customer_ID'].isnull()]

# Check the distribution of Transaction_Status in these rows
#print("Transaction_Status distribution for rows with missing Customer_ID:")
#display(missing_customer_id_rows['Transaction_Status'].value_counts(dropna=False))

In [ ]:
df['Customer_ID'].fillna('C_UNKNOWN', inplace=True)
print('Missing Customer_ID values after filling:', df['Customer_ID'].isnull().sum())
df.head()

Missing Customer_ID values after filling: 0

/tmp/ipykernel_16133/1185162617.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Customer_ID'].fillna('C_UNKNOWN', inplace=True)

,Transaction_ID,Transaction_Date,Customer_ID,Product_Name,Quantity,Price,Payment_Method,Transaction_Status
0,T0001,2024-08-02,C2205,Headphones,-5.0,$420.21,pay pal,NaN
1,T0002,2020-02-10,C3156,Coffee,469.0,-445.34202525395585,creditcard,Pending
2,T0003,2023-02-27,C2919,Tablet,-4.0,810.9930123946459,credit card,completed
3,T0004,2020-08-17,C3009,Tab,-7.0,868.6083413217348,PayPal,Pending
4,T0005,2022-10-13,C3488,Coffee Machine,-10.0,-763.1224490039416,PayPal,completed

I've filled the missing `Customer_ID` values with 'C_UNKNOWN'. This approach helps preserve the rest of the transaction data while clearly marking which customer IDs were originally unknown. You can always filter these out later if you need to analyze only transactions with identified customers.

In [ ]:
df.info()
df["Customer_ID"].head(45)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 8 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Transaction_ID      100000 non-null  object
 1   Transaction_Date    100000 non-null  datetime64[ns]
 2   Customer_ID         100000 non-null  object
 3   Product_Name        100000 non-null  object
 4   Quantity            94981 non-null   float64
 5   Price               66503 non-null   object
 6   Payment_Method      100000 non-null  object
 7   Transaction_Status  83321 non-null   object
dtypes: datetime64[ns](1), float64(1), object(6)
memory usage: 6.1+ MB

0         C2205
1         C3156
2         C2919
3         C3009
4         C3488
5         C4241
6         C1313
7         C4736
8         C3387
9         C2846
10        C1004
11        C2912
12        C1692
13        C2992
14        C3879
15        C2837
16        C3776
17         C847
18        C4871
19        C1924
20        C1137
21        C3883
22        C4877
23         C828
24        C4985
25        C1096
26        C2702
27        C3025
28        C1345
29        C3058
30        C3672
31    C_UNKNOWN
32        C1844
33        C1406
34        C2579
35         C292
36        C2492
37        C2208
38        C4687
39        C3328
40        C1693
41        C4796
42        C4046
43         C246
44        C3393
Name: Customer_ID, dtype: object

In [ ]:
import re

# Filter rows where Customer_ID is not 'C_UNKNOWN' and does not match the 'CXXXX' pattern
anomalous_customer_ids = df[(
    df['Customer_ID'] != 'C_UNKNOWN') &
    (~df['Customer_ID'].str.match(r'^C\d{4}$'))
]

print("Rows with anomalous Customer_ID (not 'C_UNKNOWN' and not matching 'CXXXX' pattern):")
display(anomalous_customer_ids.head())

Rows with anomalous Customer_ID (not 'C_UNKNOWN' and not matching 'CXXXX' pattern):

,Transaction_ID,Transaction_Date,Customer_ID,Product_Name,Quantity,Price,Payment_Method,Transaction_Status
17,T0018,2021-01-26,C847,Coffee Ma,7.0,-108.43782406112234,credit card,complete
23,T0024,2023-11-03,C828,Coffee Machine,487.0,NaN,Cash,NaN
35,T0036,2024-11-19,C292,Laptop,2.0,-596.4257637659894,pay pal,completed
43,T0044,2020-04-21,C246,Smar,-10.0,NaN,Cash,Completed
47,T0048,2023-09-09,C987,Headphones,-5.0,-527.0952322435783,Credit Card,Pending

In [ ]:
import numpy as np

def format_customer_id(customer_id):
    if pd.isna(customer_id):
        return customer_id
    customer_id = str(customer_id)
    if customer_id == 'C_UNKNOWN':
        return customer_id
    # Check if the ID starts with 'C' and the rest are digits
    if customer_id.startswith('C') and customer_id[1:].isdigit():
        num_part = customer_id[1:]
        # Pad with leading zeros if the numeric part has less than 4 digits
        if len(num_part) < 4:
            return 'C' + num_part.zfill(4)
    return customer_id

df['Customer_ID'] = df['Customer_ID'].apply(format_customer_id)

print("Customer_ID after standardization:")
display(df['Customer_ID'].value_counts(dropna=False).head(10))

Customer_ID after standardization:

Customer_ID
C_UNKNOWN    4878
C2023          37
C4347          37
C4418          36
C0876          36
C1955          35
C2583          34
C4677          34
C4618          34
C2859          34
Name: count, dtype: int64

#### Inspecting `Product_Name` Column

Before cleaning, let's inspect the `Product_Name` column to understand its current state. We'll check for unique values, their counts, and any potential issues like inconsistent casing or extra whitespace.

In [ ]:
# Check unique values and their counts
display(df['Product_Name'].value_counts())

# Check for leading/trailing spaces
print(f"Number of product names with leading/trailing spaces: {df['Product_Name'].str.strip().ne(df['Product_Name']).sum()}")

# Check for mixed case issues (by converting to lower and checking unique count)
print(f"Number of unique product names (case-insensitive): {df['Product_Name'].str.lower().nunique()}")

Product_Name
Tablet            18444
Laptop            18264
Smartphone        18257
Headphones        18107
Coffee Machine    18085
Lapt                370
Table               352
La                  347
Tabl                346
Lapto               344
Ta                  344
T                   335
Lap                 334
Tab                 330
L                   321
Smartph             234
S                   223
H                   217
He                  212
Smart               206
Head                204
Smartp              203
Headpho             203
Headphon            203
Smartphon           203
Headphone           202
Headp               201
Headph              193
Hea                 192
Sma                 191
Sm                  189
Smartpho            181
Smar                180
Coffee Ma           157
Coffee Machi        150
Coffee Machin       150
Coffee              149
Coffee Mach         149
C                   141
Coffee M            140
Cof                 137
Coffe               129
Coffee              125
Coffee Mac          123
Co                  119
Coff                114
Name: count, dtype: int64

Number of product names with leading/trailing spaces: 149
Number of unique product names (case-insensitive): 46

In [ ]:
# Standardize product names: remove leading/trailing spaces and convert to title case
df['Product_Name'] = df['Product_Name'].str.strip().str.title()

print("Product_Name after standardization")
display(df['Product_Name'].value_counts().head(20))

Product_Name after standardization

Product_Name
Tablet            18444
Laptop            18264
Smartphone        18257
Headphones        18107
Coffee Machine    18085
Lapt                370
Table               352
La                  347
Tabl                346
Ta                  344
Lapto               344
T                   335
Lap                 334
Tab                 330
L                   321
Coffee              274
Smartph             234
S                   223
H                   217
He                  212
Name: count, dtype: int64

Now that we've standardized the case and removed whitespace, let's look for more specific inconsistencies or variations that might need further attention.

In [ ]:
# Re-check unique values and their counts after initial cleaning
print("Unique Product_Name values and their counts after stripping and title casing:")
display(df['Product_Name'].value_counts())

Unique Product_Name values and their counts after stripping and title casing:

Product_Name
Tablet            18444
Laptop            18264
Smartphone        18257
Headphones        18107
Coffee Machine    18085
Lapt                370
Table               352
La                  347
Tabl                346
Ta                  344
Lapto               344
T                   335
Lap                 334
Tab                 330
L                   321
Coffee              274
Smartph             234
S                   223
H                   217
He                  212
Smart               206
Head                204
Headpho             203
Smartphon           203
Headphon            203
Smartp              203
Headphone           202
Headp               201
Headph              193
Hea                 192
Sma                 191
Sm                  189
Smartpho            181
Smar                180
Coffee Ma           157
Coffee Machin       150
Coffee Machi        150
Coffee Mach         149
C                   141
Coffee M            140
Cof                 137
Coffe               129
Coffee Mac          123
Co                  119
Coff                114
Name: count, dtype: int64

From the value_counts output, I can identify the following potential issues:

'Coffee Machine' and 'Coffee Ma': 'Coffee Ma' is likely a truncated version of 'Coffee Machine'.

'Smart Phone' and 'Smar': 'Smar' is likely a truncated version of 'Smart Phone'.

'Tab': This might be a truncated version of 'Tablet' or refer to a distinct product. Assuming it's 'Tablet' for now.

In [ ]:
df['Product_Name'] = df['Product_Name'].replace({
    'Coffee Ma': 'Coffee Machine',
    'Smar': 'Smart Phone',
    'Tab': 'Tablet',
    'Headpho':'Headphones'
})

print("Product_Name after further standardization:")
display(df['Product_Name'].value_counts())

Product_Name after further standardization:

Product_Name
Tablet            18774
Headphones        18310
Laptop            18264
Smartphone        18257
Coffee Machine    18242
Lapt                370
Table               352
La                  347
Tabl                346
Lapto               344
Ta                  344
T                   335
Lap                 334
L                   321
Coffee              274
Smartph             234
S                   223
H                   217
He                  212
Smart               206
Head                204
Smartp              203
Smartphon           203
Headphon            203
Headphone           202
Headp               201
Headph              193
Hea                 192
Sma                 191
Sm                  189
Smartpho            181
Smart Phone         180
Coffee Machin       150
Coffee Machi        150
Coffee Mach         149
C                   141
Coffee M            140
Cof                 137
Coffe               129
Coffee Mac          123
Co                  119
Coff                114
Name: count, dtype: int64

In [ ]:
!pip install fuzzywuzzy python-Levenshtein

Requirement already satisfied: fuzzywuzzy in /usr/local/lib/python3.12/dist-packages (0.18.0)
Requirement already satisfied: python-Levenshtein in /usr/local/lib/python3.12/dist-packages (0.27.3)
Requirement already satisfied: Levenshtein==0.27.3 in /usr/local/lib/python3.12/dist-packages (from python-Levenshtein) (0.27.3)
Requirement already satisfied: rapidfuzz<4.0.0,>=3.9.0 in /usr/local/lib/python3.12/dist-packages (from Levenshtein==0.27.3->python-Levenshtein) (3.14.5)

In [ ]:
import pandas as pd
from fuzzywuzzy import fuzz
from fuzzywuzzy import process

In [ ]:
def find_similar_product_names(df, column_name, threshold=70):
    unique_products = df[column_name].dropna().unique()
    similar_pairs = []

    # Convert all products to a list to iterate
    product_list = list(unique_products)

    # To avoid comparing 'A' to 'B' and 'B' to 'A', we iterate with a nested loop
    for i in range(len(product_list)):
        for j in range(i + 1, len(product_list)):
            p1 = product_list[i]
            p2 = product_list[j]
            score = fuzz.ratio(p1.lower(), p2.lower()) # Use lower() for case-insensitive comparison
            if score >= threshold:
                similar_pairs.append((p1, p2, score))
    return similar_pairs

similarities = find_similar_product_names(df, 'Product_Name', threshold=85)

if similarities:
    print(f"Found {len(similarities)} pairs of similar product names (threshold >= 70):")
    for p1, p2, score in similarities:
        print(f"  - '{p1}' and '{p2}' (Similarity: {score})")
else:
    print("No highly similar product names found with the current threshold.")

Found 36 pairs of similar product names (threshold >= 70):
  - 'Headphones' and 'Headphon' (Similarity: 89)
  - 'Headphones' and 'Headphone' (Similarity: 95)
  - 'Coffee' and 'Coffee M' (Similarity: 86)
  - 'Coffee' and 'Coffe' (Similarity: 91)
  - 'Tablet' and 'Table' (Similarity: 91)
  - 'Coffee Machine' and 'Coffee Mach' (Similarity: 88)
  - 'Coffee Machine' and 'Coffee Machin' (Similarity: 96)
  - 'Coffee Machine' and 'Coffee Machi' (Similarity: 92)
  - 'Smartphone' and 'Smart Phone' (Similarity: 95)
  - 'Smartphone' and 'Smartpho' (Similarity: 89)
  - 'Smartphone' and 'Smartphon' (Similarity: 95)
  - 'Laptop' and 'Lapto' (Similarity: 91)
  - 'Cof' and 'Coff' (Similarity: 86)
  - 'Smart Phone' and 'Smartphon' (Similarity: 90)
  - 'Coffee M' and 'Coffee Mac' (Similarity: 89)
  - 'Smartp' and 'Smart' (Similarity: 91)
  - 'Smartp' and 'Smartph' (Similarity: 92)
  - 'Smartp' and 'Smartpho' (Similarity: 86)
  - 'Headp' and 'Head' (Similarity: 89)
  - 'Headp' and 'Headph' (Similarity: 91)
  - 'Lapt' and 'Lapto' (Similarity: 89)
  - 'Lapt' and 'Lap' (Similarity: 86)
  - 'Tabl' and 'Table' (Similarity: 89)
  - 'Smartph' and 'Smartpho' (Similarity: 93)
  - 'Smartph' and 'Smartphon' (Similarity: 88)
  - 'Hea' and 'Head' (Similarity: 86)
  - 'Smartpho' and 'Smartphon' (Similarity: 94)
  - 'Headphon' and 'Headphone' (Similarity: 94)
  - 'Headphon' and 'Headph' (Similarity: 86)
  - 'Coffee Mac' and 'Coffee Mach' (Similarity: 95)
  - 'Coffee Mac' and 'Coffee Machin' (Similarity: 87)
  - 'Coffee Mac' and 'Coffee Machi' (Similarity: 91)
  - 'Coffee Mach' and 'Coffee Machin' (Similarity: 92)
  - 'Coffee Mach' and 'Coffee Machi' (Similarity: 96)
  - 'Coffee Machin' and 'Coffee Machi' (Similarity: 96)
  - 'Coff' and 'Coffe' (Similarity: 89)

The code above uses `fuzzywuzzy` to find product names that are similar to each other. It iterates through all unique product names and calculates a similarity score between each pair. If the score is above the defined `threshold` (here, 70 out of 100), it prints the pair.

In [ ]:
replacement_map = {
    'Headphon': 'Headphones',
    'Headphone': 'Headphones',
    'Headpho': 'Headphones',
    'Headp': 'Headphones',
    'Head': 'Headphones',
    'Headph': 'Headphones',
    'Hea': 'Headphones',

    'Coffee M': 'Coffee Machine',
    'Coffe': 'Coffee Machine',
    'Cof': 'Coffee Machine',
    'Coff': 'Coffee Machine',

    'Table': 'Tablet',
    'Tab': 'Tablet',
    'Tabl': 'Tablet',

    'Coffee Ma': 'Coffee Machine',
    'Coffee Mach': 'Coffee Machine',
    'Coffee Machin': 'Coffee Machine',
    'Coffee Machi': 'Coffee Machine',
    'Coffee Mac': 'Coffee Machine',

    'Smart Phone': 'Smartphone',
    'Smar': 'Smartphone',
    'Smartpho': 'Smartphone',
    'Smartphon': 'Smartphone',
    'Smart': 'Smartphone',
    'Smartp': 'Smartphone',
    'Smartph': 'Smartphone',

    'Lapto': 'Laptop',
    'Lapt': 'Laptop',
    'Lap': 'Laptop'
}

df['Product_Name'] = df['Product_Name'].replace(replacement_map)

print("Product_Name after multiple variations replaced:")
display(df['Product_Name'].value_counts())

Product_Name after multiple variations replaced:

Product_Name
Headphones        19505
Tablet            19472
Smartphone        19464
Coffee Machine    19334
Laptop            19312
La                  347
Ta                  344
T                   335
L                   321
Coffee              274
S                   223
H                   217
He                  212
Sma                 191
Sm                  189
C                   141
Co                  119
Name: count, dtype: int64

In [ ]:
replacement_map = {
    'La': 'Laptop',
    'Ta': 'Tablet',
    'T': 'Tablet',
    'L': 'Laptop',
    'Coffee': 'Coffee Machine',
    'S': 'Smartphone',
    'H': 'Headphones',
    'He': 'Headphones',
    'Sma': 'Smartphone',
    'Sm': 'Smartphone',
    'C': 'Coffee Machine',
    'Co': 'Coffee Machine'
}

df['Product_Name'] = df['Product_Name'].replace(replacement_map)

print("Product_Name after further standardization:")
display(df['Product_Name'].value_counts())

Product_Name after further standardization:

Product_Name
Tablet            20151
Smartphone        20067
Laptop            19980
Headphones        19934
Coffee Machine    19868
Name: count, dtype: int64

In [ ]:
print('Quantity column information:')
display(df['Quantity'].describe())

negative_quantities = df[df['Quantity'] < 0]['Quantity'].count()
missing_quantities = df['Quantity'].isnull().sum()

print(f"Number of negative quantities: {negative_quantities}")
print(f"Number of missing quantities: {missing_quantities}")

print("Sample of rows with negative quantities:")
display(df[df['Quantity'] < 0].head())

Quantity column information:

count    94981.000000
mean       183.883914
std        299.292365
min        -10.000000
25%         -3.000000
50%          6.000000
75%        327.000000
max       1000.000000
Name: Quantity, dtype: float64

Number of negative quantities: 31619
Number of missing quantities: 5019
Sample of rows with negative quantities:

,Transaction_ID,Transaction_Date,Customer_ID,Product_Name,Quantity,Price,Payment_Method,Transaction_Status
0,T0001,2024-08-02,C2205,Headphones,-5.0,$420.21,pay pal,NaN
2,T0003,2023-02-27,C2919,Tablet,-4.0,810.9930123946459,credit card,completed
3,T0004,2020-08-17,C3009,Tablet,-7.0,868.6083413217348,PayPal,Pending
4,T0005,2022-10-13,C3488,Coffee Machine,-10.0,-763.1224490039416,PayPal,completed
9,T0010,2021-05-06,C2846,Laptop,-1.0,404.8907066405689,creditcard,Pending

In [ ]:
import numpy as np


# Convert 'Transaction_Date' to datetime, coercing invalid dates from NaN to NaT
df['Transaction_Date'] = pd.to_datetime(df['Transaction_Date'], errors='coerce')

# Recalculate missing count after coercing invalid dates
# NaT values are considered NaN by isnull()
current_missing_count = df['Transaction_Date'].isnull().sum()

# Get a list of valid, non-missing dates
valid_dates = df['Transaction_Date'].dropna()

# Fill missing Transaction Dates by randomly sampling from existing valid dates
# Only if there are valid dates to sample from and current_missing_count > 0
if not valid_dates.empty and current_missing_count > 0:
    df.loc[df['Transaction_Date'].isnull(), 'Transaction_Date'] = np.random.choice(valid_dates, current_missing_count)

df.info()

# Store the current state of Quantity to correctly determine Transaction_Type
original_quantity_for_type = df['Quantity'].copy()

# Create 'Transaction_Type' column based on the *original* (potentially negative) quantity
df['Transaction_Type'] = original_quantity_for_type.apply(lambda x: 'Return' if x < 0 else 'Sale')

# Convert 'Quantity' to its absolute value
df['Quantity'] = df['Quantity'].abs()

# Now, recalculate the median quantity from the corrected 'Quantity' column
median_quantity_corrected = df['Quantity'].median()

# Fill any remaining missing values in 'Quantity' with this corrected median
df['Quantity'] = df['Quantity'].fillna(median_quantity_corrected)

print(f"Corrected Median Quantity used for imputation: {median_quantity_corrected}")
print(f"Missing values in 'Quantity' after imputation: {df['Quantity'].isnull().sum()}")

display(df[['Quantity', 'Transaction_Type']].head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 8 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Transaction_ID      100000 non-null  object
 1   Transaction_Date    100000 non-null  datetime64[ns]
 2   Customer_ID         100000 non-null  object
 3   Product_Name        100000 non-null  object
 4   Quantity            94981 non-null   float64
 5   Price               66503 non-null   object
 6   Payment_Method      100000 non-null  object
 7   Transaction_Status  83321 non-null   object
dtypes: datetime64[ns](1), float64(1), object(6)
memory usage: 6.1+ MB
Corrected Median Quantity used for imputation: 8.0
Missing values in 'Quantity' after imputation: 0

   Quantity Transaction_Type
0       5.0           Return
1     469.0             Sale
2       4.0           Return
3       7.0           Return
4      10.0           Return

In [ ]:
# Inspect the 'Price' column
print('Price column information:')
display(df['Price'].describe())

# Check data type
print(f"Data type of 'Price' column: {df['Price'].dtype}")

# Check for missing values
missing_prices = df['Price'].isnull().sum()
print(f"Number of missing prices: {missing_prices}")

# Display sample of non-numeric prices if any
# To do this, first attempt to convert to numeric, coercing errors
non_numeric_prices = df[pd.to_numeric(df['Price'], errors='coerce').isnull()]['Price']
print(f"Number of non-numeric price entries (excluding NaN): {non_numeric_prices.count()}")
print("Sample of non-numeric price entries (excluding NaN):")
display(non_numeric_prices.value_counts().head(10))

Price column information:

count                  66503
unique                 65757
top       -882.8581558218868
freq                       3
Name: Price, dtype: object

Data type of 'Price' column: object
Number of missing prices: 33497
Number of non-numeric price entries (excluding NaN): 6640
Sample of non-numeric price entries (excluding NaN):

Price
$-874.99    3
$-651.74    3
$661.29     3
$-260.08    3
$182.38     3
$103.82     3
$814.62     3
$52.88      2
$985.31     2
$-281.42    2
Name: count, dtype: int64

In [ ]:
import numpy as np

# Remove non-numeric characters like '$' and convert to numeric, coercing errors
df['Price'] = df['Price'].astype(str).str.replace(r'[^\d.-]', '', regex=True)
df['Price'] = pd.to_numeric(df['Price'], errors='coerce')

# Calculate the median of the 'Price' column AFTER cleaning
median_price = df['Price'].median()

# Fill missing values in 'Price' with the median
df['Price'] = df['Price'].fillna(median_price)

print(f"Median price used for imputation: {median_price}")
print(f"Number of missing prices after imputation: {df['Price'].isnull().sum()}")

df.info()
display(df.head())

Median price used for imputation: 51.608527493328126
Number of missing prices after imputation: 0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 9 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Transaction_ID      100000 non-null  object
 1   Transaction_Date    100000 non-null  datetime64[ns]
 2   Customer_ID         100000 non-null  object
 3   Product_Name        100000 non-null  object
 4   Quantity            100000 non-null  float64
 5   Price               100000 non-null  float64
 6   Payment_Method      100000 non-null  object
 7   Transaction_Status  83321 non-null   object
 8   Transaction_Type    100000 non-null  object
dtypes: datetime64[ns](1), float64(2), object(6)
memory usage: 6.9+ MB

,Transaction_ID,Transaction_Date,Customer_ID,Product_Name,Quantity,Price,Payment_Method,Transaction_Status,Transaction_Type
0,T0001,2024-08-02,C2205,Headphones,5.0,420.210000,pay pal,NaN,Return
1,T0002,2020-02-10,C3156,Coffee Machine,469.0,-445.342025,creditcard,Pending,Sale
2,T0003,2023-02-27,C2919,Tablet,4.0,810.993012,credit card,completed,Return
3,T0004,2020-08-17,C3009,Tablet,7.0,868.608341,PayPal,Pending,Return
4,T0005,2022-10-13,C3488,Coffee Machine,10.0,-763.122449,PayPal,completed,Return

In [ ]:
# Inspect the 'Transaction_Status' column
print('Transaction_Status column information:')
display(df['Transaction_Status'].value_counts(dropna=False))

# Check for missing values
missing_status = df['Transaction_Status'].isnull().sum()
print(f"Number of missing Transaction_Status values: {missing_status}")

Transaction_Status column information:

Transaction_Status
Failed       16795
complete     16717
completed    16687
NaN          16679
Pending      16595
Completed    16527
Name: count, dtype: int64

Number of missing Transaction_Status values: 16679

In [ ]:
print('Rows with negative prices:')
display(df[df['Price'] < 0].head())

Rows with negative prices:

,Transaction_ID,Transaction_Date,Customer_ID,Product_Name,Quantity,Price,Payment_Method,Transaction_Status,Transaction_Type
1,T0002,2020-02-10,C3156,Coffee Machine,469.0,-445.342025,creditcard,pending,Sale
4,T0005,2022-10-13,C3488,Coffee Machine,10.0,-763.122449,PayPal,completed,Return
7,T0008,2021-06-14,C4736,Headphones,669.0,-86.921269,Cash,pending,Sale
10,T0011,2023-12-28,C1004,Laptop,10.0,-600.839309,PayPal,completed,Sale
16,T0017,2020-07-07,C3776,Smartphone,236.0,-94.557265,credit card,pending,Sale

In [ ]:
print('Relationship between negative prices and transaction type:')
display(df[df['Price'] < 0]['Transaction_Type'].value_counts())

Relationship between negative prices and transaction type:

Transaction_Type
Sale      22819
Return    10376
Name: count, dtype: int64

In [ ]:
df['Price'] = df['Price'].abs()

print('Price column after converting to absolute values:')
display(df['Price'].describe())

df.info()

Price column after converting to absolute values:

count    100000.000000
mean        366.587548
std         316.198080
min          50.028806
25%          51.608527
50%         286.286239
75%         643.521641
max         999.987698
Name: Price, dtype: float64

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 9 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Transaction_ID      100000 non-null  object
 1   Transaction_Date    100000 non-null  datetime64[ns]
 2   Customer_ID         100000 non-null  object
 3   Product_Name        100000 non-null  object
 4   Quantity            100000 non-null  float64
 5   Price               100000 non-null  float64
 6   Payment_Method      100000 non-null  object
 7   Transaction_Status  100000 non-null  object
 8   Transaction_Type    100000 non-null  object
dtypes: datetime64[ns](1), float64(2), object(6)
memory usage: 6.9+ MB

In [ ]:
# Inspect the 'Transaction_Status' column
print('Transaction_Status column information:')
display(df['Transaction_Status'].value_counts(dropna=False))

# Check for missing values
missing_status = df['Transaction_Status'].isnull().sum()
print(f"Number of missing Transaction_Status values: {missing_status}")

Transaction_Status column information:

Transaction_Status
completed    49931
pending      33274
failed       16795
Name: count, dtype: int64

Number of missing Transaction_Status values: 0

In [ ]:
# Standardize Transaction_Status values
df['Transaction_Status'] = df['Transaction_Status'].str.lower().replace({
    'complete': 'completed'
}).str.title()

# Fill missing values with 'pending'
df['Transaction_Status'] = df['Transaction_Status'].fillna('pending').str.title()

print("Transaction_Status after standardization and imputation:")
display(df['Transaction_Status'].value_counts(dropna=False))

df.info()

Transaction_Status after standardization and imputation:

Transaction_Status
Completed    49931
Pending      33274
Failed       16795
Name: count, dtype: int64

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 10 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Transaction_ID      100000 non-null  object
 1   Transaction_Date    100000 non-null  datetime64[ns]
 2   Customer_ID         100000 non-null  object
 3   Product_Name        100000 non-null  object
 4   Quantity            100000 non-null  float64
 5   Price               100000 non-null  float64
 6   Payment_Method      100000 non-null  object
 7   Transaction_Status  100000 non-null  object
 8   Transaction_Type    100000 non-null  object
 9   Price_USD           100000 non-null  object
dtypes: datetime64[ns](1), float64(2), object(7)
memory usage: 7.6+ MB

In [ ]:
# Identify rows where Quantity is negative but Price is positive
discrepant_transactions = df[(df['Transaction_Type'] == 'Return') & (df['Price'] > 0)]

print("Rows with negative Quantity (Return) but positive Price:")
display(discrepant_transactions.head(10))

Rows with negative Quantity (Return) but positive Price:

,Transaction_ID,Transaction_Date,Customer_ID,Product_Name,Quantity,Price,Payment_Method,Transaction_Status,Transaction_Type
0,T0001,2024-08-02,C2205,Headphones,5.0,420.210000,pay pal,pending,Return
2,T0003,2023-02-27,C2919,Tablet,4.0,810.993012,credit card,completed,Return
3,T0004,2020-08-17,C3009,Tablet,7.0,868.608341,PayPal,pending,Return
4,T0005,2022-10-13,C3488,Coffee Machine,10.0,763.122449,PayPal,completed,Return
9,T0010,2021-05-06,C2846,Laptop,1.0,404.890707,creditcard,pending,Return
14,T0015,2024-08-28,C3879,Headphones,2.0,523.842758,credit card,pending,Return
15,T0016,2023-01-31,C2837,Laptop,3.0,51.608527,creditcard,pending,Return
19,T0020,2020-09-10,C1924,Headphones,6.0,51.608527,pay pal,pending,Return
26,T0027,2020-12-17,C2702,Coffee Machine,5.0,555.613348,creditcard,completed,Return
28,T0029,2021-10-06,C1345,Smartphone,5.0,295.765151,PayPal,pending,Return

In [ ]:
# Create a formatted 'Price_USD' column for display
df['Price_USD'] = df['Price'].apply(lambda x: f"${x:.2f}")

print("DataFrame with formatted Price_USD column:")
display(df[['Price', 'Price_USD']].head())

DataFrame with formatted Price_USD column:

        Price Price_USD
0  420.210000   $420.21
1  445.342025   $445.34
2  810.993012   $810.99
3  868.608341   $868.61
4  763.122449   $763.12

In [ ]:
# Check the value counts for Transaction_Status in these discrepant rows
print("Transaction_Status distribution for discrepant rows:")
display(discrepant_transactions['Transaction_Status'].value_counts(dropna=False))

Transaction_Status distribution for discrepant rows:

Transaction_Status
completed    15863
pending      10501
failed        5255
Name: count, dtype: int64

In [ ]:
# Standardize Transaction_Status values
df['Transaction_Status'] = df['Transaction_Status'].str.lower().replace({
    'complete': 'completed'
})

# Fill missing values with 'pending'
df['Transaction_Status'] = df['Transaction_Status'].fillna('pending')

print("Transaction_Status after standardization and imputation:")
display(df['Transaction_Status'].value_counts(dropna=False))

df.info()

Transaction_Status after standardization and imputation:

Transaction_Status
completed    49931
pending      33274
failed       16795
Name: count, dtype: int64

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 9 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Transaction_ID      100000 non-null  object
 1   Transaction_Date    100000 non-null  datetime64[ns]
 2   Customer_ID         100000 non-null  object
 3   Product_Name        100000 non-null  object
 4   Quantity            100000 non-null  float64
 5   Price               100000 non-null  float64
 6   Payment_Method      100000 non-null  object
 7   Transaction_Status  100000 non-null  object
 8   Transaction_Type    100000 non-null  object
dtypes: datetime64[ns](1), float64(2), object(6)
memory usage: 6.9+ MB

In [ ]:
# Inspect the 'Payment_Method' column
print('Payment_Method column information:')
display(df['Payment_Method'].value_counts(dropna=False))

# Check for missing values
missing_payment_methods = df['Payment_Method'].isnull().sum()
print(f"Number of missing Payment_Method values: {missing_payment_methods}")

Payment_Method column information:

Payment_Method
Credit Card    14433
creditcard     14384
pay pal        14357
PayPal         14262
Cash           14212
credit card    14198
PayPal         14154
Name: count, dtype: int64

Number of missing Payment_Method values: 0

In [ ]:
df['Payment_Method'] = df['Payment_Method'].str.strip().str.title().replace({
    'Creditcard': 'Credit Card',
    'Paypal': 'PayPal'
})

print("Payment_Method after standardization:")
display(df['Payment_Method'].value_counts(dropna=False))

Payment_Method after standardization:

Payment_Method
Credit Card    43015
PayPal         42773
Cash           14212
Name: count, dtype: int64

In [ ]:
df.head(20)

,Transaction_ID,Transaction_Date,Customer_ID,Product_Name,Quantity,Price,Payment_Method,Transaction_Status,Transaction_Type,Price_USD
0,T0001,2024-08-02,C2205,Headphones,5.0,420.210000,PayPal,Pending,Return,$420.21
1,T0002,2020-02-10,C3156,Coffee Machine,469.0,445.342025,Credit Card,Pending,Sale,$445.34
2,T0003,2023-02-27,C2919,Tablet,4.0,810.993012,Credit Card,Completed,Return,$810.99
3,T0004,2020-08-17,C3009,Tablet,7.0,868.608341,PayPal,Pending,Return,$868.61
4,T0005,2022-10-13,C3488,Coffee Machine,10.0,763.122449,PayPal,Completed,Return,$763.12
5,T0006,2021-10-26,C4241,Smartphone,598.0,51.608527,PayPal,Completed,Sale,$51.61
6,T0007,2024-05-25,C1313,Laptop,10.0,51.608527,Credit Card,Completed,Sale,$51.61
7,T0008,2021-06-14,C4736,Headphones,669.0,86.921269,Cash,Pending,Sale,$86.92
8,T0009,2023-06-25,C3387,Tablet,10.0,461.701984,PayPal,Pending,Sale,$461.70
9,T0010,2021-05-06,C2846,Laptop,1.0,404.890707,Credit Card,Pending,Return,$404.89
10,T0011,2023-12-28,C1004,Laptop,10.0,600.839309,PayPal,Completed,Sale,$600.84
11,T0012,2021-08-24,C2912,Tablet,608.0,51.608527,PayPal,Completed,Sale,$51.61
12,T0013,2020-03-18,C1692,Smartphone,564.0,51.608527,Cash,Completed,Sale,$51.61
13,T0014,2020-06-19,C2992,Coffee Machine,696.0,905.514730,Credit Card,Failed,Sale,$905.51
14,T0015,2024-08-28,C3879,Headphones,2.0,523.842758,Credit Card,Pending,Return,$523.84
15,T0016,2023-01-31,C2837,Laptop,3.0,51.608527,Credit Card,Pending,Return,$51.61
16,T0017,2020-07-07,C3776,Smartphone,236.0,94.557265,Credit Card,Pending,Sale,$94.56
17,T0018,2021-01-26,C0847,Coffee Machine,7.0,108.437824,Credit Card,Completed,Sale,$108.44
18,T0019,2024-02-19,C4871,Smartphone,8.0,51.608527,PayPal,Pending,Sale,$51.61
19,T0020,2020-09-10,C1924,Headphones,6.0,51.608527,PayPal,Pending,Return,$51.61
20,T0021,2024-10-03,C1137,Coffee Machine,856.0,488.862649,Credit Card,Failed,Sale,$488.86
21,T0022,2021-12-17,C3883,Smartphone,9.0,51.608527,Credit Card,Completed,Sale,$51.61
22,T0023,2023-06-26,C4877,Tablet,538.0,733.829228,PayPal,Completed,Sale,$733.83
23,T0024,2023-11-03,C0828,Coffee Machine,487.0,51.608527,Cash,Pending,Sale,$51.61
24,T0025,2022-11-18,C4985,Tablet,114.0,276.936320,PayPal,Pending,Sale,$276.94
25,T0026,2020-01-01,C1096,Coffee Machine,654.0,51.608527,PayPal,Completed,Sale,$51.61
26,T0027,2020-12-17,C2702,Coffee Machine,5.0,555.613348,Credit Card,Completed,Return,$555.61
27,T0028,2023-03-04,C3025,Smartphone,7.0,797.340000,PayPal,Completed,Sale,$797.34
28,T0029,2021-10-06,C1345,Smartphone,5.0,295.765151,PayPal,Pending,Return,$295.77
29,T0030,2021-10-16,C3058,Headphones,5.0,51.608527,PayPal,Failed,Sale,$51.61
30,T0031,2024-07-17,C3672,Tablet,5.0,787.994076,Credit Card,Completed,Return,$787.99
31,T0032,2023-10-05,C_UNKNOWN,Laptop,7.0,51.608527,Credit Card,Completed,Return,$51.61
32,T0033,2020-10-07,C1844,Coffee Machine,3.0,546.780835,PayPal,Failed,Return,$546.78
33,T0034,2021-07-27,C1406,Coffee Machine,3.0,120.680996,Credit Card,Completed,Sale,$120.68
34,T0035,2022-07-25,C2579,Coffee Machine,485.0,970.280000,Credit Card,Completed,Sale,$970.28
35,T0036,2024-11-19,C0292,Laptop,2.0,596.425764,PayPal,Completed,Sale,$596.43
36,T0037,2025-01-03,C2492,Smartphone,10.0,711.710000,PayPal,Pending,Return,$711.71
37,T0038,2020-06-18,C2208,Laptop,8.0,51.608527,Credit Card,Failed,Sale,$51.61
38,T0039,2020-07-20,C4687,Tablet,9.0,51.608527,PayPal,Completed,Sale,$51.61
39,T0040,2021-10-04,C3328,Headphones,7.0,51.608527,PayPal,Failed,Sale,$51.61
40,T0041,2023-10-20,C1693,Laptop,865.0,51.608527,Credit Card,Completed,Sale,$51.61
41,T0042,2021-08-04,C4796,Coffee Machine,8.0,51.608527,Credit Card,Failed,Sale,$51.61
42,T0043,2021-07-18,C4046,Smartphone,10.0,51.608527,Cash,Pending,Return,$51.61
43,T0044,2020-04-21,C0246,Smartphone,10.0,51.608527,Cash,Completed,Return,$51.61
44,T0045,2020-09-27,C3393,Smartphone,5.0,653.386740,Credit Card,Pending,Return,$653.39
45,T0046,2020-05-24,C2797,Coffee Machine,825.0,788.770503,PayPal,Completed,Sale,$788.77
46,T0047,2024-10-09,C2200,Laptop,8.0,51.608527,Cash,Completed,Sale,$51.61
47,T0048,2023-09-09,C0987,Headphones,5.0,527.095232,Credit Card,Pending,Return,$527.10
48,T0049,2020-06-18,C4480,Laptop,762.0,51.608527,Credit Card,Completed,Sale,$51.61
49,T0050,2021-04-23,C_UNKNOWN,Tablet,6.0,969.720000,PayPal,Completed,Return,$969.72

In [ ]:
df.to_csv('cleaned_financial_transactions.csv', index=False)
print("Cleaned data saved to 'cleaned_financial_transactions.csv'")

Cleaned data saved to 'cleaned_financial_transactions.csv'